### ISSUE TITLE
Please release 0.3.2 on PyPI

### ISSUE THREAD

**Issue by wagnerflo** [truenas/py-sysctl#14]
Currently there's only 0.2 on PyPI which doesn't compile on newer Python interpreters. I've built and tested the current Git master / 0.3.2 which works perfectly.

Being able to install from PyPI using pip and specify it as a dependency in my project would be great.

**Comment by uyota** [comment]
+1 for releasing a new version via PyPI, please.

I started writing a script that depends on py-sysctl.
'pip install sysctl' fails with compiler error while 'pkg install py37-sysctl' installs newer code base and works okay.

Thanks in advance.

**Comment by uyota** [comment]
Thanks.  I checked pip install now succeeds with 0.3.3 release.  Please close the issue.
